In [4]:
!pip install --upgrade scikit-learn

     |████████████████████████████████| 23.2 MB 1.6 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [10]:
!pip install transformers
!pip install tensorboardx
!pip install simpletransformers

     |████████████████████████████████| 2.9 MB 5.3 MB/s 
     |████████████████████████████████| 56 kB 4.1 MB/s 
     |████████████████████████████████| 3.3 MB 38.8 MB/s 
     |████████████████████████████████| 895 kB 36.9 MB/s 
     |████████████████████████████████| 596 kB 43.6 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
     |████████████████████████████████| 124 kB 5.5 MB/s 
     |████████████████████████████████| 231 kB 5.5 MB/s 
     |████████████████████████████████| 8.3 MB 31.2 MB/s 
     |████████████████████████████████| 43 kB 2.0 MB/s 
     |████████████████████████████████| 290 kB 43.5 MB/s 
     |████████████████████████████████| 1.7 MB 30.3 MB/s 
     |████████████████████████████████| 1.2 MB 34.4 MB/s 
     |████████████████████████████████| 180 kB 46.5 MB/s 
     |████████████████████████████████| 139 kB 39.8 MB/s 
     |████████████████████████████████| 97 kB 

In [ ]:
!pip install nltk

In [1]:
import pandas as pd
import numpy as np

from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_validate
from sklearn.svm import SVC

from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, make_scorer

In [2]:
X_train = pd.read_csv('/content/ru/train.csv', sep=';')
X_test = pd.read_csv('/content/ru/test.csv', sep=';')
y_train = pd.read_csv('/content/ru/target.csv', sep=';')

In [ ]:
X_train

In [3]:
y_train.info

<bound method DataFrame.info of         id  target_1  target_2  target_3  target_4  target_5  target_6
0    ID002       5.8       6.2       6.3       5.5       6.0       5.0
1    ID003       6.0       6.2       7.0       5.8       5.2       5.0
2    ID004       6.2       6.4       8.0       5.5       6.8       5.5
3    ID006       6.2       6.6       8.3       6.5       7.0       6.3
4    ID007       6.0       6.2       7.7       5.0       6.0       5.0
..     ...       ...       ...       ...       ...       ...       ...
166  ID216       5.0       5.0       5.0       5.0       4.0       4.0
167  ID217       5.0       6.0       8.0       5.0       6.0       5.0
168  ID218       5.0       5.0       6.0       4.0       6.0       5.0
169  ID219       5.0       6.0       6.0       5.0       5.0       5.0
170  ID220       5.0       5.0       6.0       5.0       5.0       6.0

[171 rows x 7 columns]>

In [9]:
for i in y_train.columns[1:]:
  y_train[str(i)] /= 10

y_train

id  target_1  target_2  target_3  target_4  target_5  target_6
0    ID002      0.58      0.62      0.63      0.55      0.60      0.50
1    ID003      0.60      0.62      0.70      0.58      0.52      0.50
2    ID004      0.62      0.64      0.80      0.55      0.68      0.55
3    ID006      0.62      0.66      0.83      0.65      0.70      0.63
4    ID007      0.60      0.62      0.77      0.50      0.60      0.50
..     ...       ...       ...       ...       ...       ...       ...
166  ID216      0.50      0.50      0.50      0.50      0.40      0.40
167  ID217      0.50      0.60      0.80      0.50      0.60      0.50
168  ID218      0.50      0.50      0.60      0.40      0.60      0.50
169  ID219      0.50      0.60      0.60      0.50      0.50      0.50
170  ID220      0.50      0.50      0.60      0.50      0.50      0.60

[171 rows x 7 columns]

In [ ]:
y_train

id  target_1  target_2  target_3  target_4  target_5  target_6
0    ID002      0.58      0.62      0.63      0.55      0.60      0.50
1    ID003      0.60      0.62      0.70      0.58      0.52      0.50
2    ID004      0.62      0.64      0.80      0.55      0.68      0.55
3    ID006      0.62      0.66      0.83      0.65      0.70      0.63
4    ID007      0.60      0.62      0.77      0.50      0.60      0.50
..     ...       ...       ...       ...       ...       ...       ...
166  ID216      0.50      0.50      0.50      0.50      0.40      0.40
167  ID217      0.50      0.60      0.80      0.50      0.60      0.50
168  ID218      0.50      0.50      0.60      0.40      0.60      0.50
169  ID219      0.50      0.60      0.60      0.50      0.50      0.50
170  ID220      0.50      0.50      0.60      0.50      0.50      0.60

[171 rows x 7 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_val = train_test_split(X_train, test_size=0.2, shuffle=False)
y_train = y_train.set_index('id') 

In [12]:
from transformers import BertTokenizer
from transformers import BertTokenizer, BertModel
# Load the BERT tokenizer.
print('Loading BERT tokenizer...')
tokenizer = BertTokenizer.from_pretrained('sberbank-ai/sbert_large_nlu_ru', do_lower_case=False)

Loading BERT tokenizer...


Downloading:   0%|          | 0.00/1.70M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/323 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/655 [00:00<?, ?B/s]

In [ ]:
max_len = 0

# For every sentence...
for sent in X_train['text']:
    # Tokenize the text and add `[CLS]` and `[SEP]` tokens.
    input_ids = tokenizer.encode(sent, add_special_tokens=False)
    if max_len < len(input_ids):
      print('New max_len:', len(input_ids))
    # Update the maximum sentence length. 
    max_len = max(max_len, len(input_ids))

print('Max sentence length: ', max_len)

New max_len: 8
New max_len: 86
New max_len: 113
New max_len: 120
New max_len: 126
New max_len: 179
New max_len: 196
New max_len: 261
New max_len: 277
New max_len: 282
New max_len: 567
New max_len: 574
Max sentence length:  574


In [ ]:
import torch

In [ ]:
def tokenize_sentence(text):
  encoded_dict = tokenizer.encode_plus(
                        text,                      # Sentence to encode.
                        add_special_tokens = True, # Add '[CLS]' and '[SEP]'
                        max_length = 64,           # Pad & truncate all sentences.
                        truncation = True,
                        pad_to_max_length = True,
                        return_tensors = 'pt',     # Return pytorch tensors.
                   )
  return encoded_dict['input_ids']

def tokenize_sentences(sentences_in, labels_in):
  input_ids = []
  labels = []
  for i in range(0, len(sentences_in)):
    input_id = tokenize_sentence(sentences_in[i])
    input_ids.append(input_id)
  input_ids = torch.cat(input_ids, dim=0)
  labels = torch.tensor(labels_in)
  return input_ids, labels

Model training

In [ ]:
X_train, X_val = X_train.loc[X_train['text'] != '-'], X_val.loc[X_val['text'] != '-']

In [ ]:
X_train, X_val

(         id                                               text
 0     ID002                Добрый день, Никита. Благодарю Вас!
 1     ID002  Добрый день, Элена. Я разделяю Ваше видение зн...
 2     ID002       Добрый день, Герасим. Спасибо за информацию.
 4     ID002  Добрый день, Нелли. Оба кандидата достойные и ...
 5     ID002  Добрый день, Елизавета. Полагаю, что принципиа...
 ...     ...                                                ...
 7155  ID198  Готовьте материал и назначайте встречу. Рынок ...
 7156  ID198  Герасим, прошу разобраться и доложить о решени...
 7158  ID198   Спасибо. Внесите встречу в календарь, пожалуйста
 7159  ID198  Елизавета, предварительно подготовленный и мат...
 7162  ID198  Мария, добрый день. Мы согласуем готовность к ...
 
 [4346 rows x 2 columns],
          id                                               text
 7163  ID198  Евгения, руководители прямого подчинения, руко...
 7165  ID198  Герасим, Алекс, с учетом ситуации в Тайване ра...
 7166  ID198

In [ ]:
y_train

target_1  target_2  target_3  target_4  target_5  target_6
id                                                               
ID002      0.58      0.62      0.63      0.55      0.60      0.50
ID003      0.60      0.62      0.70      0.58      0.52      0.50
ID004      0.62      0.64      0.80      0.55      0.68      0.55
ID006      0.62      0.66      0.83      0.65      0.70      0.63
ID007      0.60      0.62      0.77      0.50      0.60      0.50
...         ...       ...       ...       ...       ...       ...
ID216      0.50      0.50      0.50      0.50      0.40      0.40
ID217      0.50      0.60      0.80      0.50      0.60      0.50
ID218      0.50      0.50      0.60      0.40      0.60      0.50
ID219      0.50      0.60      0.60      0.50      0.50      0.50
ID220      0.50      0.50      0.60      0.50      0.50      0.60

[171 rows x 6 columns]

In [ ]:
labels_train = list(map(lambda x: y_train.loc[x].tolist(), X_train['id']))
labels_val = list(map(lambda x: y_train.loc[x].tolist(), X_val['id']))

In [ ]:
X_train['labels'] = labels_train
X_val['labels'] = labels_val

In [ ]:
X_train

id  ...                              labels
0     ID002  ...  [0.58, 0.62, 0.63, 0.55, 0.6, 0.5]
1     ID002  ...  [0.58, 0.62, 0.63, 0.55, 0.6, 0.5]
2     ID002  ...  [0.58, 0.62, 0.63, 0.55, 0.6, 0.5]
4     ID002  ...  [0.58, 0.62, 0.63, 0.55, 0.6, 0.5]
5     ID002  ...  [0.58, 0.62, 0.63, 0.55, 0.6, 0.5]
...     ...  ...                                 ...
7155  ID198  ...      [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
7156  ID198  ...      [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
7158  ID198  ...      [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
7159  ID198  ...      [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
7162  ID198  ...      [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]

[4346 rows x 3 columns]

In [ ]:
X_val

id  ...                          labels
7163  ID198  ...  [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
7165  ID198  ...  [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
7166  ID198  ...  [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
7169  ID198  ...  [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
7171  ID198  ...  [0.6, 0.7, 0.7, 0.5, 0.6, 0.6]
...     ...  ...                             ...
8941  ID220  ...  [0.5, 0.5, 0.6, 0.5, 0.5, 0.6]
8944  ID220  ...  [0.5, 0.5, 0.6, 0.5, 0.5, 0.6]
8946  ID220  ...  [0.5, 0.5, 0.6, 0.5, 0.5, 0.6]
8947  ID220  ...  [0.5, 0.5, 0.6, 0.5, 0.5, 0.6]
8948  ID220  ...  [0.5, 0.5, 0.6, 0.5, 0.5, 0.6]

[1046 rows x 3 columns]

In [ ]:
input_ids_train, labels_train = tokenize_sentences(X_train['text'].tolist(), labels_train)
input_ids_val, labels_val = tokenize_sentences(X_val['text'].tolist(), labels_val)

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2132: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


In [ ]:
from transformers import BertForSequenceClassification, AdamW, BertConfig

model = BertForSequenceClassification.from_pretrained(
    "sberbank-ai/sbert_large_nlu_ru", 
    num_labels = 6, 
    output_attentions = False, 
    output_hidden_states = False, 
)

if torch.cuda.is_available():

  model.cuda()

2021-07-20 20:07:56.428041: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0


Downloading:   0%|          | 0.00/655 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.71G [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at sberbank-ai/sbert_large_nlu_ru and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
from torch.utils.data import TensorDataset, random_split

train_dataset = TensorDataset(input_ids_train, labels_train)
val_dataset = TensorDataset(input_ids_val, labels_val)

In [ ]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

batch_size = 16

train_dataloader = DataLoader(
            train_dataset, 
            sampler = RandomSampler(train_dataset), # Select batches randomly
            batch_size = batch_size # Trains with this batch size.
        )


validation_dataloader = DataLoader(
            val_dataset, .
            sampler = SequentialSampler(val_dataset), 
            batch_size = batch_size 
        )


In [ ]:
optimizer = AdamW(model.parameters(),
                  lr = 0.000001, # args.learning_rate - default is 5e-5, our notebook had 2e-5
                  eps = 1e-8 # args.adam_epsilon  - default is 1e-8.
                )


In [ ]:
from transformers import get_linear_schedule_with_warmup

epochs = 1
total_steps = len(train_dataloader) * epochs

scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = 0, # Default value in run_glue.py
                                            num_training_steps = total_steps)

In [ ]:
import time
import datetime

def format_time(elapsed):
 
    elapsed_rounded = int(round((elapsed)))
    
    return str(datetime.timedelta(seconds=elapsed_rounded))


In [ ]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla V100-SXM2-16GB


In [ ]:
import random
import numpy as np
import torch
import time

# This training code is based on the `run_glue.py` script here:
# https://github.com/huggingface/transformers/blob/5bfcd0485ece086ebcbed2d008813037968a9e58/examples/run_glue.py#L128

# Set the seed value all over the place to make this reproducible.
seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

training_stats = []

total_t0 = time.time()

# For each epoch...
for epoch_i in range(0, epochs):
    
    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))


    t0 = time.time()


    total_train_loss = 0

    
    model.train()


    for step, batch in enumerate(train_dataloader):

        
        if step % 40 == 0 and not step == 0:
            
            elapsed = format_time(time.time() - t0)
            
          
            print('  Batch {:>5,}  of  {:>5,}.    Elapsed: {:}.'.format(step, len(train_dataloader), elapsed))

   
        b_input_ids = batch[0].to(device)
        b_labels = batch[1].to(device)

        model.zero_grad()        


        outputs = model(b_input_ids, 
                        labels=b_labels)
        loss = outputs.loss
        logits = outputs.logits

       
        total_train_loss += loss.item()

       
        loss.backward()


        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optimizer.step()

       
        scheduler.step()

    avg_train_loss = total_train_loss / len(train_dataloader)            
    
.
    training_time = format_time(time.time() - t0)

    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epcoh took: {:}".format(training_time))
        


    print("")
    print("Running Validation...")

    t0 = time.time()

    model.eval()


    total_eval_accuracy = 0
    total_eval_loss = 0
    nb_eval_steps = 0


    for batch in validation_dataloader:

        b_input_ids = batch[0].to(device)
        b_labels = batch[1].to(device)

        with torch.no_grad():        

            outputs = model(b_input_ids, 
                            labels=b_labels)
            (loss, logits) = (outputs.loss, outputs.logits)
            

        total_eval_loss += loss.item()

        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()


        

    avg_val_accuracy = total_eval_accuracy / len(validation_dataloader)
    print("  Accuracy: {0:.2f}".format(avg_val_accuracy))

    
    avg_val_loss = total_eval_loss / len(validation_dataloader)
    
    
    validation_time = format_time(time.time() - t0)
    
    print("  Validation Loss: {0:.2f}".format(avg_val_loss))
    print("  Validation took: {:}".format(validation_time))

    
    training_stats.append(
        {
            'epoch': epoch_i + 1,
            'Training Loss': avg_train_loss,
            'Valid. Loss': avg_val_loss,
            'Valid. Accur.': avg_val_accuracy,
            'Training Time': training_time,
            'Validation Time': validation_time
        }
    )

print("")
print("Training complete!")

print("Total training took {:} (h:mm:ss)".format(format_time(time.time()-total_t0)))


======== Epoch 1 / 1 ========
Training...
  Batch    40  of    272.    Elapsed: 0:00:09.
  Batch    80  of    272.    Elapsed: 0:00:19.
  Batch   120  of    272.    Elapsed: 0:00:28.
  Batch   160  of    272.    Elapsed: 0:00:37.
  Batch   200  of    272.    Elapsed: 0:00:46.
  Batch   240  of    272.    Elapsed: 0:00:56.

  Average training loss: 0.67
  Training epcoh took: 0:01:03

Running Validation...
  Accuracy: 0.00
  Validation Loss: 0.70
  Validation took: 0:00:04

Training complete!
Total training took 0:01:07 (h:mm:ss)


In [ ]:
def tokenize_sentences_out(sentences_in):

  input_ids = []
  for i in range(0, len(sentences_in)):

    input_id = tokenize_sentence(sentences_in[i])
    input_ids.append(input_id)
    
  input_ids = torch.cat(input_ids, dim=0)

  return input_ids

In [ ]:
pred_input_ids = tokenize_sentences_out(X_val['text'].tolist())

In [ ]:
def predict(input_ids_in):
    model.eval()
    dataset = TensorDataset(input_ids_in)

    dataloader = DataLoader(
            dataset,  # The training samples.
            batch_size = batch_size # Trains with this batch size.
        )
    predictions = []
    for batch in dataloader:
        input_ids = batch[0].to(device)
        with torch.no_grad():
  
            outputs = model(input_ids)
        
        logits = outputs[0]

     
        logits = logits.detach().cpu().numpy()
        predictions.extend(logits)
    return predictions
def predict_by_dataloader(dataloader):
    model.eval()

    predictions = []
    for batch in dataloader:
        input_ids = batch[0].to(device)
        with torch.no_grad():
        
            outputs = model(input_ids)
        
        logits = outputs[0]

        logits = logits.detach().cpu().numpy()
        predictions.extend(logits)
    return predictions

In [ ]:
torch.cuda.empty_cache()

In [ ]:
predictions_val = predict_by_dataloader(validation_dataloader)

In [ ]:
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_absolute_percentage_error as mape

In [ ]:
predictions_val

[array([0.417398  , 0.82017314, 0.81048673, 0.3088695 , 0.6249936 ,
        0.04651072], dtype=float32),
 array([0.38118201, 0.34219244, 0.5919937 , 0.16592963, 0.754921  ,
        0.30251035], dtype=float32),
 array([0.01036617, 0.54428875, 0.74766237, 0.22985195, 0.6172644 ,
        0.15970138], dtype=float32),
 array([0.12329439, 0.57176334, 0.7669389 , 0.26092064, 0.5118886 ,
        0.15239783], dtype=float32),
 array([0.4968325 , 0.64921737, 0.87137526, 0.3703962 , 0.56693774,
        0.2837146 ], dtype=float32),
 array([0.3477486 , 0.55432755, 0.6952799 , 0.37910992, 0.5336648 ,
        0.07097518], dtype=float32),
 array([0.5478729 , 0.6311809 , 0.87095445, 0.20207712, 0.62639195,
        0.3858988 ], dtype=float32),
 array([0.14782725, 0.6711212 , 0.8526588 , 0.3463129 , 0.6290013 ,
        0.2887223 ], dtype=float32),
 array([0.31359866, 0.58990705, 0.7546167 , 0.4556807 , 0.63497263,
        0.24373436], dtype=float32),
 array([0.08481657, 0.65770805, 0.7452412 , 0.40912774,

In [ ]:
for target_num in range(6):
  print(f'MAE on {target_num + 1}:', mae(list(map(lambda x: x[target_num], X_val['labels'].tolist())), list(map(lambda x: x[target_num], predictions_val))))
  print(f'MAPE on {target_num + 1}:', mape(list(map(lambda x: x[target_num], X_val['labels'].tolist())), list(map(lambda x: x[target_num], predictions_val))))
print('MAE:', mae(X_val['labels'].tolist(), predictions_val))
print('MAPE:', mape(X_val['labels'].tolist(), predictions_val))

MAE on 1: 0.2704692780765797
MAPE on 1: 0.5276337096309593
MAE on 2: 0.0962141797373901
MAPE on 2: 0.1722725767679231
MAE on 3: 0.1934441922271685
MAPE on 3: 0.36132988664816396
MAE on 4: 0.20223034117584532
MAPE on 4: 0.40614622030030273
MAE on 5: 0.12501542553960937
MAPE on 5: 0.2384868532064415
MAE on 6: 0.28394596424831564
MAPE on 6: 0.5703037889645087
MAE: 0.19521989683415186
MAPE: 0.3793621725863832


In [ ]:
predictions_train = predict_by_dataloader(train_dataloader)
for target_num in range(6):
  print(f'MAE on {target_num + 1}:', mae(list(map(lambda x: x[target_num], X_train['labels'].tolist())), list(map(lambda x: x[target_num], predictions_train))))
  print(f'MAPE on {target_num + 1}:', mape(list(map(lambda x: x[target_num], X_train['labels'].tolist())), list(map(lambda x: x[target_num], predictions_train))))
print('MAE:', mae(X_train['labels'].tolist(), predictions_train))
print('MAPE:', mape(X_train['labels'].tolist(), predictions_train))

MAE on 1: 0.3154591343840087
MAPE on 1: 0.5309141178298376
MAE on 2: 0.10231118951958003
MAPE on 2: 0.1559506301120517
MAE on 3: 0.13832044911930433
MAPE on 3: 0.2114317431139802
MAE on 4: 0.29243016461721705
MAPE on 4: 0.5065477662931697
MAE on 5: 0.11744360489795629
MAPE on 5: 0.17715877619376064
MAE on 6: 0.34679943549886194
MAPE on 6: 0.6221650250806797
MAE: 0.21879399633948438
MAPE: 0.3673613431039133


In [ ]:
predictions_train

[array([0.37806982, 0.6980184 , 0.8945383 , 0.16898222, 0.6881471 ,
        0.36323178], dtype=float32),
 array([0.13728318, 0.4837507 , 0.7400619 , 0.2999513 , 0.4412151 ,
        0.10339404], dtype=float32),
 array([0.3729161 , 0.6422841 , 1.0571021 , 0.20614399, 0.5961771 ,
        0.28889024], dtype=float32),
 array([0.18183292, 0.5676557 , 0.8512905 , 0.25805777, 0.44646886,
        0.213141  ], dtype=float32),
 array([0.24574485, 0.5253001 , 0.7476888 , 0.29340133, 0.55030274,
        0.20291495], dtype=float32),
 array([0.13172105, 0.54064745, 0.76608926, 0.28504065, 0.4774345 ,
        0.19355856], dtype=float32),
 array([0.2260027 , 0.6904166 , 0.6062598 , 0.42145213, 0.7059904 ,
        0.147768  ], dtype=float32),
 array([0.1594785 , 0.5562872 , 0.7233334 , 0.3182403 , 0.52830577,
        0.12093376], dtype=float32),
 array([0.25441387, 0.70895207, 0.8857014 , 0.3155989 , 0.53024876,
        0.06514566], dtype=float32),
 array([0.48461354, 0.47837466, 0.97710794, 0.32916707,

In [ ]:
X_train.id.unique()

array(['ID002', 'ID003', 'ID004', 'ID006', 'ID007', 'ID009', 'ID011',
       'ID012', 'ID014', 'ID018', 'ID019', 'ID020', 'ID021', 'ID022',
       'ID023', 'ID026', 'ID027', 'ID029', 'ID030', 'ID031', 'ID032',
       'ID034', 'ID035', 'ID036', 'ID038', 'ID039', 'ID040', 'ID042',
       'ID044', 'ID045', 'ID046', 'ID047', 'ID048', 'ID049', 'ID050',
       'ID053', 'ID054', 'ID057', 'ID060', 'ID062', 'ID063', 'ID064',
       'ID065', 'ID067', 'ID068', 'ID069', 'ID070', 'ID072', 'ID073',
       'ID074', 'ID075', 'ID076', 'ID077', 'ID078', 'ID080', 'ID081',
       'ID082', 'ID083', 'ID084', 'ID086', 'ID089', 'ID091', 'ID092',
       'ID096', 'ID097', 'ID098', 'ID099', 'ID100', 'ID101', 'ID102',
       'ID103', 'ID104', 'ID105', 'ID107', 'ID108', 'ID110', 'ID111',
       'ID112', 'ID113', 'ID117', 'ID118', 'ID119', 'ID120', 'ID121',
       'ID123', 'ID126', 'ID127', 'ID129', 'ID130', 'ID131', 'ID132',
       'ID136', 'ID137', 'ID138', 'ID139', 'ID140', 'ID143', 'ID144',
       'ID145', 'ID1

In [ ]:
 train.values.tolist()

[['ID002', [0.58, 0.62, 0.63, 0.55, 0.6, 0.5]],
 ['ID003', [0.6, 0.62, 0.7, 0.58, 0.52, 0.5]],
 ['ID004', [0.62, 0.64, 0.8, 0.55, 0.6799999999999999, 0.55]],
 ['ID006', [0.62, 0.6599999999999999, 0.8300000000000001, 0.65, 0.7, 0.63]],
 ['ID007', [0.6, 0.62, 0.77, 0.5, 0.6, 0.5]],
 ['ID009', [0.52, 0.62, 0.6, 0.63, 0.6, 0.5]],
 ['ID011', [0.52, 0.5599999999999999, 0.7, 0.55, 0.6799999999999999, 0.5]],
 ['ID012', [0.64, 0.62, 0.63, 0.65, 0.6, 0.6799999999999999]],
 ['ID014', [0.58, 0.64, 0.63, 0.65, 0.54, 0.55]],
 ['ID018', [0.48, 0.58, 0.73, 0.5, 0.6799999999999999, 0.45]],
 ['ID019', [0.54, 0.62, 0.73, 0.58, 0.72, 0.53]],
 ['ID020', [0.58, 0.5599999999999999, 0.67, 0.53, 0.62, 0.4]],
 ['ID021', [0.45999999999999996, 0.6, 0.53, 0.5, 0.6, 0.48]],
 ['ID022', [0.54, 0.6599999999999999, 0.63, 0.6, 0.52, 0.5]],
 ['ID023', [0.54, 0.64, 0.67, 0.55, 0.62, 0.55]],
 ['ID026',
  [0.5599999999999999,
   0.6799999999999999,
   0.7,
   0.5,
   0.6799999999999999,
   0.53]],
 ['ID027',
  [0.4400000000

In [ ]:
import json
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler

file = '/content/data_ranking.json'
with open(file) as train_file:
    data = json.load(train_file)


train = pd.DataFrame.from_dict(data, orient='index', columns=[ "id", "target"])
data = pd.DataFrame.from_dict(data, orient='index', columns=[ "id", "data", "target"])
train["id"] = train.index
data["id"] = data.index
train.index = [i for i in range(151)]

train_df = pd.DataFrame()
train_df["id"] = X_train.id
train_df["targets"] = np.nan


tak = train.values.tolist()
blet = train_df.values.tolist()
for i in blet:
  for j in tak:
    if i[0] == j[0]:
      i[1] = j[1]

      
train_df["targets"] = [i[1] for i in blet]
train_df["labels"] = [i for i in np.vstack(data.data)]

In [ ]:
train_df['targets'][0]

[0.58, 0.62, 0.63, 0.55, 0.6, 0.5]

In [ ]:
train_df['labels'][0]

array([0.22867982, 0.4822962 , 0.70773846, 0.29310766, 0.45309606,
       0.07660536])

In [ ]:
train_df["MAE"] = [i for i in list_of_mae[:4346]]
train_df_min_MAE = train_df.loc[train_df.groupby(["id"])["MAE"].idxmin()]

In [ ]:
train_df_min_MAE

In [ ]:
!pip install catboost 

In [ ]:
!pip install xgboost

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
#from catboost import Pool, CatBoostRegressor
from sklearn import svm
from sklearn import linear_model
from sklearn.linear_model import ElasticNet
#from xgboost import XGBRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

X = np.array([i for i in train_df["labels"]]) 
y = np.array([i for i in train_df["targets"]])

my_alpha = 0.1
my_l1ratio = 0.5

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42, shuffle=False)

reg =  LinearRegression(Ridge(alpha=0.005))
reg.fit(X_train, y_train)



/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass fit_intercept=Ridge(alpha=0.005) as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


LinearRegression(fit_intercept=Ridge(alpha=0.005))

In [ ]:
pred = reg.predict(X_test)
for i in pred:
  for j in y_test:
    print("MAE", mae(j, i))
    print("MAPE", mape(j, i))

In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import max_error

pred = reg.predict(X_test)
r2_score(y_test, pred,  multioutput='variance_weighted')

-0.14890279472154497

In [ ]:
pred

array([[0.59821833, 0.65960353, 0.70519116, 0.57154627, 0.65283187,
        0.55721807],
       [0.59465349, 0.65453808, 0.7038916 , 0.5687179 , 0.64979922,
        0.55741839],
       [0.58461267, 0.65453078, 0.69179965, 0.56602379, 0.64229702,
        0.54624104],
       ...,
       [0.59076279, 0.65677662, 0.69586687, 0.56946322, 0.64943436,
        0.54879206],
       [0.59283066, 0.65791964, 0.70056427, 0.57105929, 0.65190845,
        0.55270536],
       [0.60209989, 0.66744341, 0.71120158, 0.57587354, 0.6608332 ,
        0.56713347]])

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate


scoring = {'mae': make_scorer(mean_absolute_error), 
               'mape': make_scorer(mean_absolute_percentage_error)}

scores = cross_validate(reg,
                        X_train,
                        y_train,
                        cv=6,
                        scoring=scoring)
scores

{'fit_time': array([0.01094389, 0.00166297, 0.00167465, 0.00162196, 0.00160909,
        0.00160933]),
 'score_time': array([0.00102043, 0.00094366, 0.00089955, 0.00084448, 0.00089192,
        0.00089908]),
 'test_mae': array([0.05492831, 0.05688831, 0.0555201 , 0.05792   , 0.06884733,
        0.0741179 ]),
 'test_mape': array([0.09847114, 0.09732578, 0.08488475, 0.09183581, 0.11478927,
        0.1194744 ])}

In [ ]:
X_test

array([[0.36638466, 0.67306894, 0.84155446, 0.29326311, 0.67391127,
        0.18083216],
       [0.36011255, 0.56909984, 0.92559963, 0.3134602 , 0.6508984 ,
        0.23009434],
       [0.2349067 , 0.45720908, 0.77952653, 0.19257283, 0.55041015,
        0.12135768],
       ...,
       [0.34154725, 0.51434225, 0.7211656 , 0.23541419, 0.50665486,
        0.13744666],
       [0.3472231 , 0.52289242, 0.78056121, 0.21645601, 0.61098146,
        0.16726601],
       [0.33190879, 0.73228502, 0.71372741, 0.38020915, 0.63111597,
        0.46103889]])

In [ ]:
import itertools
from pprint import pprint

def ranking_pred(ID_name):


  list_of_mae = []

  list_pred = list([i for i in X_val[X_val.id == str(ID_name)].predictions])
  combination_list = list(itertools.combinations(itertools.chain(*list_pred), 6))

  for i in combination_list:

    mae_value = mae([Xval_min_MAE.id == str(ID_name)].labels, i)

    if mae_value < Xval_min_MAE[X_val.id == str(ID_name)].MAE:

      dict_mae = {mae_value : i}
      list_of_mae.append(dict_mae)

  return list_of_mae 

In [ ]:
!pip install flair

In [ ]:
pred_ID198 = ranking_pred("ID198")